### ISSUE TITLE
'New Private Window' crashes Dooble

### ISSUE THREAD

**Issue by DavidMcKenna** [bitwiseworks/dooble-os2#4] opened 2022-04-25 12:58 UTC
Clicking on the 'hamburger' icon (3 horizontal lines) in the upper right corner, then choosing 'New Private Window' causes Dooble to disappear. No exceptq report is produced.

 This is the latest rpm version of Dooble on ArcaOS 5.0.7.

**Comment by DavidMcKenna** [comment] 2022-04-25 14:09
Just tried in multi-process mode and it works, so this crash only happens in single process mode.

**Comment by dmik** [comment] 2022-04-25 15:46
I'm afraid Chromium may simply not support private windows in single-process mode. Note also that single-process mode is not officially supported (and never will be). It is there mostly for testing and development purposes.

And Dooble does not actually crash: it simply exits (normally in the sense that it does not crash) after spitting this to the console (you can redirect or run it with `sh -c dooble.exe` to see the output):
```
Single mode supports only single profile.
```

I'm therefore closing this as not a bug. But a note will be added to the readme.

**Closed by dmik** 2022-04-25 15:46 UTC
